### PR TITLE
Add trump

### PR DESCRIPTION
**Pull request by Slaqer**
Added a trump gif.

### CODE REVIEW

**Comment by AbstractBeliefs** [comment]
You'll need to make an adjustment to the `themes`, which maps emote strings (like :trump:) to files as well.

Do you know currently how people are getting the packs? I know the eurosquad distribution site is down, are people still using the git updater?

**Comment by Slaqer** [comment]
Added the mapping in the theme file.

We are using a direct link to the [github zip](https://github.com/Berach/BERACHS_COMPLETE_PIDGIN/archive/master.zip) file to distribute it. So for people to receive the update they'll have to re-download the pack.

**Comment by AbstractBeliefs** [comment]
Which alliance are you from, by the way?

**Comment by Slaqer** [comment]
TEST, what about you?

**Comment by AbstractBeliefs** [comment]
TEST-ish. Ex. I've been looking to get back in for the war that's going down. I go by kline eto on the forums but I can't log in anymore :cry:

**Comment by Slaqer** [comment]
Oh cool. And yeah you should definitely get in for this war, it's probably some of the funnest I've ever had in EVE (a bunch of old vets coming back and we get to shoot goons). I'll be sure to keep an eye out for your name in game if you resub again, mine is Slaqer.

**Comment by SpinnerMaster** [comment]
Yo Kline come join DIX. We are on the front lines and having a fuckload of fun.

**Pull request merged**
