### PR TITLE
Never_forget_1962.jpeg.gif

### PR DESCRIPTION
**Pull request by Apapin**

### CODE REVIEW

**Comment by Berach** [comment]
Leaving this open until a crying flag emote gets made.

**Comment by panacuba** [comment]
Mexico FLAG is not crying, Why should the cuban? Lets celebrate that merica and cuba are buddies again, so, merge ti hehehe.

**Comment by Berach** [comment]
Also not accepting because there isn't a blank line between [default] and :cuba:

**Comment by Apapin** [comment]
Wow. You're a blank line.

**Pull request closed without merging**
